# Generated by Django 3.1.2 on 2020-11-29 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='client_id')),
                ('password', models.CharField(default='000000', max_length=20, verbose_name='pwd')),
            ],
            options={
                'verbose_name': 'clientInfo',
                'verbose_name_plural': 'clientInfo',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='question_id')),
                ('title', models.TextField(verbose_name='question_title')),
                ('optionA', models.CharField(max_length=100, verbose_name='option_a')),
                ('optionB', models.CharField(max_length=100, verbose_name='option_b')),
                ('optionC', models.CharField(max_length=100, verbose_name='option_c')),
                ('optionD', models.CharField(max_length=100, verbose_name='option_d')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10, verbose_name='answer')),
            ],
            options={
                'verbose_name': 'questionPool',
                'verbose_name_plural': 'questionPool',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=20, verbose_name='investor_type')),
                ('cid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.client')),
            ],
            options={
                'verbose_name': 'questionnaire_result',
                'verbose_name_plural': 'questionnaire_result',
                'db_table': 'result',
            },
        ),
    ]
