# Generated by Django 3.1.2 on 2020-11-30 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='question_page')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.client')),
                ('pid', models.ManyToManyField(to='questionnaire.Question')),
            ],
            options={
                'verbose_name': 'questionPage',
                'verbose_name_plural': 'questionPage',
                'db_table': 'page',
            },
        ),
    ]
