# Generated by Django 3.1.2 on 2020-11-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='question_page',
            field=models.CharField(default='', max_length=20, verbose_name='qp'),
        ),
    ]
