# Generated by Django 3.1.2 on 2020-12-01 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_client_question_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
