# Generated by Django 3.1.2 on 2020-12-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20201130_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionInvtype',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='question_id')),
                ('title', models.TextField(verbose_name='question_title')),
                ('optionA', models.CharField(max_length=100, verbose_name='option_a')),
                ('optionB', models.CharField(max_length=100, verbose_name='option_b')),
                ('optionC', models.CharField(max_length=100, verbose_name='option_c')),
                ('optionD', models.CharField(max_length=100, verbose_name='option_d')),
            ],
            options={
                'verbose_name': 'Invtype questions',
                'verbose_name_plural': 'Invtype questions',
                'db_table': 'questionInvtype',
            },
        ),
        migrations.CreateModel(
            name='QuestionSLR',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='question_id')),
                ('title', models.TextField(verbose_name='question_title')),
                ('optionA', models.CharField(max_length=100, verbose_name='option_a')),
                ('optionB', models.CharField(max_length=100, verbose_name='option_b')),
                ('optionC', models.CharField(max_length=100, verbose_name='option_c')),
                ('optionD', models.CharField(max_length=100, verbose_name='option_d')),
            ],
            options={
                'verbose_name': 'SLR questions',
                'verbose_name_plural': 'SLR questions',
                'db_table': 'questionSLR',
            },
        ),
        migrations.CreateModel(
            name='QuestionTolerance',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='question_id')),
                ('title', models.TextField(verbose_name='question_title')),
                ('optionA', models.CharField(max_length=100, verbose_name='option_a')),
                ('optionB', models.CharField(max_length=100, verbose_name='option_b')),
                ('optionC', models.CharField(max_length=100, verbose_name='option_c')),
                ('optionD', models.CharField(max_length=100, verbose_name='option_d')),
            ],
            options={
                'verbose_name': 'Tolerance questions',
                'verbose_name_plural': 'Tolerance questions',
                'db_table': 'questionTolerance',
            },
        ),
        migrations.CreateModel(
            name='QuestionTrends',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='question_id')),
                ('title', models.TextField(verbose_name='question_title')),
                ('optionA', models.CharField(max_length=100, verbose_name='option_a')),
                ('optionB', models.CharField(max_length=100, verbose_name='option_b')),
                ('optionC', models.CharField(max_length=100, verbose_name='option_c')),
                ('optionD', models.CharField(max_length=100, verbose_name='option_d')),
            ],
            options={
                'verbose_name': 'Trends questions',
                'verbose_name_plural': 'Trends questions',
                'db_table': 'questionTrends',
            },
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionESG',
        ),
        migrations.AlterModelOptions(
            name='questionesg',
            options={'verbose_name': 'ESG questions', 'verbose_name_plural': 'ESG questions'},
        ),
        migrations.AlterModelTable(
            name='questionesg',
            table='questionESG',
        ),
    ]
