# Generated by Django 3.1.2 on 2020-12-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20201130_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionesg',
            name='optionA',
            field=models.CharField(max_length=500, verbose_name='option_a'),
        ),
        migrations.AlterField(
            model_name='questionesg',
            name='optionB',
            field=models.CharField(max_length=500, verbose_name='option_b'),
        ),
        migrations.AlterField(
            model_name='questionesg',
            name='optionC',
            field=models.CharField(max_length=500, verbose_name='option_c'),
        ),
        migrations.AlterField(
            model_name='questionesg',
            name='optionD',
            field=models.CharField(max_length=500, verbose_name='option_d'),
        ),
        migrations.AlterField(
            model_name='questioninvtype',
            name='optionA',
            field=models.CharField(max_length=500, verbose_name='option_a'),
        ),
        migrations.AlterField(
            model_name='questioninvtype',
            name='optionB',
            field=models.CharField(max_length=500, verbose_name='option_b'),
        ),
        migrations.AlterField(
            model_name='questioninvtype',
            name='optionC',
            field=models.CharField(max_length=500, verbose_name='option_c'),
        ),
        migrations.AlterField(
            model_name='questioninvtype',
            name='optionD',
            field=models.CharField(max_length=500, verbose_name='option_d'),
        ),
        migrations.AlterField(
            model_name='questionslr',
            name='optionA',
            field=models.CharField(max_length=500, verbose_name='option_a'),
        ),
        migrations.AlterField(
            model_name='questionslr',
            name='optionB',
            field=models.CharField(max_length=500, verbose_name='option_b'),
        ),
        migrations.AlterField(
            model_name='questionslr',
            name='optionC',
            field=models.CharField(max_length=500, verbose_name='option_c'),
        ),
        migrations.AlterField(
            model_name='questionslr',
            name='optionD',
            field=models.CharField(max_length=500, verbose_name='option_d'),
        ),
        migrations.AlterField(
            model_name='questiontolerance',
            name='optionA',
            field=models.CharField(max_length=500, verbose_name='option_a'),
        ),
        migrations.AlterField(
            model_name='questiontolerance',
            name='optionB',
            field=models.CharField(max_length=500, verbose_name='option_b'),
        ),
        migrations.AlterField(
            model_name='questiontolerance',
            name='optionC',
            field=models.CharField(max_length=500, verbose_name='option_c'),
        ),
        migrations.AlterField(
            model_name='questiontolerance',
            name='optionD',
            field=models.CharField(max_length=500, verbose_name='option_d'),
        ),
        migrations.AlterField(
            model_name='questiontrends',
            name='optionA',
            field=models.CharField(max_length=500, verbose_name='option_a'),
        ),
        migrations.AlterField(
            model_name='questiontrends',
            name='optionB',
            field=models.CharField(max_length=500, verbose_name='option_b'),
        ),
        migrations.AlterField(
            model_name='questiontrends',
            name='optionC',
            field=models.CharField(max_length=500, verbose_name='option_c'),
        ),
        migrations.AlterField(
            model_name='questiontrends',
            name='optionD',
            field=models.CharField(max_length=500, verbose_name='option_d'),
        ),
    ]
