# Generated by Django 3.1.2 on 2020-12-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20201201_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='question_page',
        ),
    ]
