# Generated by Django 3.1.2 on 2020-12-06 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_remove_client_question_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20, verbose_name='question_page')),
                ('qid', models.CharField(max_length=10, verbose_name='question_id')),
                ('answer', models.CharField(max_length=10, verbose_name='answer')),
                ('cid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.client')),
            ],
            options={
                'verbose_name': 'questionnaire_answer',
                'verbose_name_plural': 'questionnaire_answer',
                'db_table': 'answer',
            },
        ),
    ]
