# Generated by Django 3.1.2 on 2020-12-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_auto_20201212_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontrends',
            name='optionE',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_e'),
        ),
        migrations.AddField(
            model_name='questiontrends',
            name='optionF',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_f'),
        ),
        migrations.AddField(
            model_name='questiontrends',
            name='optionG',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_g'),
        ),
        migrations.AddField(
            model_name='questiontrends',
            name='optionH',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_h'),
        ),
        migrations.AddField(
            model_name='questiontrends',
            name='optionI',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_i'),
        ),
        migrations.AddField(
            model_name='questiontrends',
            name='optionJ',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_j'),
        ),
        migrations.AddField(
            model_name='questiontrends',
            name='optionK',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_k'),
        ),
        migrations.AddField(
            model_name='questiontrends',
            name='optionL',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_l'),
        ),
        migrations.AddField(
            model_name='questiontrends',
            name='optionM',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_m'),
        ),
        migrations.AddField(
            model_name='questiontrends',
            name='optionN',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_n'),
        ),
        migrations.AddField(
            model_name='questiontrends',
            name='optionO',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_o'),
        ),
        migrations.AddField(
            model_name='questiontrends',
            name='optionP',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_p'),
        ),
        migrations.AddField(
            model_name='questiontrends',
            name='optionQ',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_q'),
        ),
        migrations.AddField(
            model_name='questiontrends',
            name='optionR',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_r'),
        ),
        migrations.AddField(
            model_name='questiontrends',
            name='optionS',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_s'),
        ),
        migrations.AddField(
            model_name='questiontrends',
            name='optionT',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_t'),
        ),
        migrations.AddField(
            model_name='questiontrends',
            name='optionU',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_u'),
        ),
        migrations.AddField(
            model_name='questiontrends',
            name='optionV',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_v'),
        ),
        migrations.AddField(
            model_name='questiontrends',
            name='optionW',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_w'),
        ),
        migrations.AlterField(
            model_name='questiontrends',
            name='optionA',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_a'),
        ),
        migrations.AlterField(
            model_name='questiontrends',
            name='optionB',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_b'),
        ),
        migrations.AlterField(
            model_name='questiontrends',
            name='optionC',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_c'),
        ),
        migrations.AlterField(
            model_name='questiontrends',
            name='optionD',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_d'),
        ),
    ]
