# Generated by Django 3.1.2 on 2020-12-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20201215_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionesg',
            name='id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='question_id'),
        ),
        migrations.AlterField(
            model_name='questionslr',
            name='id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='question_id'),
        ),
        migrations.AlterField(
            model_name='questiontolerance',
            name='id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='question_id'),
        ),
        migrations.AlterField(
            model_name='questiontrends',
            name='id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='question_id'),
        ),
    ]
