# Generated by Django 3.1.2 on 2020-12-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_auto_20201215_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.CharField(max_length=100, verbose_name='investor_type'),
        ),
    ]
