# Generated by Django 3.1.2 on 2020-12-16 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_auto_20201215_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultSLR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slr', models.CharField(max_length=100, verbose_name='slr')),
                ('cid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.client')),
            ],
            options={
                'verbose_name': 'SLR result',
                'verbose_name_plural': 'SLR result',
                'db_table': 'result_slr',
            },
        ),
    ]
