# Generated by Django 3.1.2 on 2020-12-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0014_resultslr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_growth', models.FloatField(verbose_name='income_growth_rate')),
                ('expense_growth', models.FloatField(verbose_name='expense_growth_rate')),
                ('discounting_factor', models.FloatField(verbose_name='discounting_factor')),
            ],
            options={
                'verbose_name': 'discount parameters',
                'verbose_name_plural': 'discount parameters',
                'db_table': 'discount',
            },
        ),
    ]
