# Generated by Django 3.1.2 on 2020-12-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0015_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=100, verbose_name='answer'),
        ),
    ]
