# Generated by Django 3.1.2 on 2020-12-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0016_auto_20201225_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionesg',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='question_id'),
        ),
        migrations.AlterField(
            model_name='questioninvtype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='question_id'),
        ),
        migrations.AlterField(
            model_name='questionslr',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='question_id'),
        ),
        migrations.AlterField(
            model_name='questiontolerance',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='question_id'),
        ),
        migrations.AlterField(
            model_name='questiontrends',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='question_id'),
        ),
    ]
