# Generated by Django 3.1.2 on 2020-12-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0017_auto_20201225_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontrends',
            name='only',
            field=models.CharField(blank=True, max_length=500, verbose_name='only_option'),
        ),
    ]
