# Generated by Django 3.1.2 on 2020-12-31 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0018_questiontrends_only'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiontrends',
            old_name='only',
            new_name='optiononly',
        ),
    ]
