# Generated by Django 3.1.2 on 2020-12-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0019_auto_20201230_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionesg',
            name='optiononly',
            field=models.CharField(blank=True, max_length=500, verbose_name='only_option'),
        ),
    ]
