# Generated by Django 3.1.2 on 2020-12-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0020_questionesg_optiononly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionesg',
            name='optionB',
            field=models.CharField(blank=True, max_length=500, verbose_name='option_b'),
        ),
    ]
