# Generated by Django 3.1.2 on 2021-01-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0021_auto_20201231_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=1000, verbose_name='answer'),
        ),
    ]
