# Generated by Django 3.2 on 2021-04-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0023_auto_20210108_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionslr',
            name='textbox',
            field=models.TextField(blank=True, verbose_name='dialogue_box2'),
        ),
    ]
