# Generated by Django 3.2 on 2021-04-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0024_alter_questionslr_textbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionslr',
            name='textbox2',
            field=models.TextField(blank=True, verbose_name='dialogue_box_2'),
        ),
        migrations.AlterField(
            model_name='questionslr',
            name='textbox',
            field=models.TextField(blank=True, verbose_name='dialogue_box'),
        ),
    ]
