# Generated by Django 3.2 on 2021-04-24 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0025_auto_20210422_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_esg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='questionnaire.questionesg'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_inv_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='questionnaire.questioninvtype'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_slr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='questionnaire.questionslr'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_tolerance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='questionnaire.questiontolerance'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_trend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='questionnaire.questiontrends'),
        ),
        migrations.AddField(
            model_name='answer',
            name='textbox',
            field=models.TextField(blank=True, null=True, verbose_name='dialogue_box'),
        ),
        migrations.AddField(
            model_name='answer',
            name='textbox2',
            field=models.TextField(blank=True, null=True, verbose_name='dialogue_box_2'),
        ),
    ]
