# Generated by Django 3.2 on 2021-04-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0026_auto_20210424_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=5000, null=True, verbose_name='answer'),
        ),
    ]
